name: TOSBombs
author: fcartegnie
category: Widgets
tags: [tos, atari, crash, row of bombs]
demo: http://fcartegnie.github.com/TOSBombs/
docs: http://github.com/fcartegnie/TOSBombs/blob/master/Docs/TOSBombs.md 
